[build]
  command = "npm run export"

[[plugins]]
package = "netlify-plugin-cache-nextjs"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[headers]]
for = "/*"
[headers.values]
  Cache-Control = "public, max-age=3600"

[[headers]]
for = "/nvc"
[headers.values]
  Cache-Control = "public, max-age=600"
