name: update NVC data

on:
  schedule:
    # check every 10 minutes on Monday in the update window
    - cron: 3/10 14-16 * * 1
    # check every hour on Monday outside the update window
    - cron: 38 0-13,17-23 * * 1
    # check every day for the rest of the week
    - cron: 38 8 * * 0,2-6
  push:
  workflow_dispatch:

defaults:
  run:
    working-directory: data/nvc

jobs:
  update-nvc-data:
    name: update NVC data
    runs-on: ubuntu-latest
    outputs:
      new_commit_sha: ${{ steps.commit.outputs.commit_sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Set up poetry
        uses: Gr1N/setup-poetry@v7
      - name: Cache poetry virtualenv
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-data-nvc-${{ hashFiles('data/nvc/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Run script
        run: poetry run python main.py
      - name: Commit changes
        id: commit
        uses: EndBug/add-and-commit@v7

  build:
    uses: underyx/visawhen/.github/workflows/build.yml@main
    needs: [update-nvc-data]
    with:
      ref: ${{ needs.update-nvc-data.outputs.new_commit_sha }}

  deploy:
    uses: underyx/visawhen/.github/workflows/deploy.yml@main
    needs: [update-nvc-data, build]
    with:
      ref: ${{ needs.update-nvc-data.outputs.new_commit_sha }}
