name: update NVC data
on:
  schedule:
    # check every 10 minutes on Monday in the update window
    - cron: 3/10 14-16 * * 1
    # check every hour on Monday outside the update window
    - cron: 38 0-13,17-23 * * 1
    # check every day for the rest of the week
    - cron: 38 8 * * 0,2-6
  push:
  workflow_dispatch:
jobs:
  update-data:
    name: update data
    runs-on: ubuntu-latest
    working-directory: data/nvc
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Set up poetry
        uses: Gr1N/setup-poetry@v7
      - name: Cache poetry virtualenv
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-data-nvc-${{ hashFiles('data/nvc/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Run script
        run: poetry run python main.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
